SOURCE_GROUPS = {
    "all": {"label": "全部", "home_label": "所有站点"},
    "image": {"label": "图片站点", "home_label": "图片站点"},
    "figure": {"label": "手办站点", "home_label": "手办站点"},
    "anime": {"label": "动画站点", "home_label": "动画站点"},
    "asset": {"label": "3D站点", "home_label": "3D站点"},
}

GROUP_ORDER = ["all", "image", "figure", "anime", "asset"]

SITE_REGISTRY = {
    "danbooru": {
        "group": "image",
        "label": "Danbooru",
        "title": "标签结构最强的图站",
        "description": "更适合按角色、作品、画师和标签搜索，细粒度标签最丰富。",
        "best_for": "角色图、作品 fanart、作者风格图。",
        "examples": ["asuna_(sao)", "genshin_impact", "raiden_shogun", "mika_pikazo"],
        "hint_tags": ["角色", "作品", "画师", "tag"],
        "supports_search": True,
        "supports_mixed_home": True,
        "is_available": True,
        "status_note": None,
        "links": [
            {"label": "主页", "url": "https://danbooru.donmai.us"},
            {"label": "API", "url": "https://danbooru.donmai.us/wiki_pages/help:api"},
        ],
    },
    "safebooru": {
        "group": "image",
        "label": "Safebooru",
        "title": "更偏安全向的 booru 图站",
        "description": "适合快速找公开安全向的角色和作品图片。",
        "best_for": "角色图、作品图、通用标签图像。",
        "examples": ["asuna", "fate series", "blue archive", "miku"],
        "hint_tags": ["角色", "作品", "标签"],
        "supports_search": True,
        "supports_mixed_home": True,
        "is_available": True,
        "status_note": None,
        "links": [{"label": "主页", "url": "https://safebooru.org"}],
    },
    "zerochan": {
        "group": "image",
        "label": "Zerochan",
        "title": "角色 / 作品导向更明显的图集站",
        "description": "更适合直接搜角色名和作品名，角色图集感更强。",
        "best_for": "角色图集、作品图集、壁纸式浏览。",
        "examples": ["Asuna", "Genshin Impact", "Hatsune Miku", "Azur Lane"],
        "hint_tags": ["角色", "作品"],
        "supports_search": True,
        "supports_mixed_home": True,
        "is_available": True,
        "status_note": None,
        "links": [{"label": "主页", "url": "https://www.zerochan.net"}],
    },
    "yandere": {
        "group": "image",
        "label": "Yande.re",
        "title": "高质量二次元图站",
        "description": "适合按角色、作品和标签快速找高分辨率插画。",
        "best_for": "高清图、壁纸图、tag 搜索。",
        "examples": ["asuna", "hatsune_miku", "blue_archive", "genshin_impact"],
        "hint_tags": ["角色", "作品", "tag"],
        "supports_search": True,
        "supports_mixed_home": True,
        "is_available": True,
        "status_note": None,
        "links": [
            {"label": "主页", "url": "https://yande.re"},
            {"label": "API", "url": "https://yande.re/help/api"},
        ],
    },
    "pixiv": {
        "group": "image",
        "label": "Pixiv",
        "title": "插画社区",
        "description": "角色图和画师作品密度很高，但公开抓取通常需要登录态或额外策略。",
        "best_for": "画师作品、角色图、插画发现。",
        "examples": ["アスナ", "初音ミク", "ブルーアーカイブ", "原神"],
        "hint_tags": ["角色", "作品", "画师"],
        "supports_search": True,
        "supports_mixed_home": False,
        "is_available": False,
        "status_note": "Pixiv 当前通常需要登录态或额外抓取策略，后端公开搜索暂未接通",
        "links": [{"label": "主页", "url": "https://www.pixiv.net"}],
    },
    "gelbooru": {
        "group": "image",
        "label": "Gelbooru",
        "title": "公开 booru 图站",
        "description": "标签导向的图站，但当前运行环境里的公开接口请求会被安全校验拦截。",
        "best_for": "角色图、tag 图像。",
        "examples": ["asuna", "hatsune_miku", "blue_archive", "genshin_impact"],
        "hint_tags": ["角色", "作品", "tag"],
        "supports_search": True,
        "supports_mixed_home": False,
        "is_available": False,
        "status_note": "Gelbooru 当前运行环境访问公开接口会返回 Cloudflare 401，后端暂未接通",
        "links": [
            {"label": "主页", "url": "https://gelbooru.com"},
            {"label": "DAPI", "url": "https://gelbooru.com/index.php?page=help&topic=dapi"},
        ],
    },
    "konachan": {
        "group": "image",
        "label": "Konachan",
        "title": "壁纸导向图站",
        "description": "适合搜壁纸式图像和经典 tag 图站内容。",
        "best_for": "壁纸图、角色图、tag 搜索。",
        "examples": ["asuna", "hatsune_miku", "azur_lane", "landscape"],
        "hint_tags": ["角色", "作品", "tag"],
        "supports_search": True,
        "supports_mixed_home": False,
        "is_available": False,
        "status_note": "Konachan 文档公开，但当前运行环境访问 post.json 会触发浏览器验证",
        "links": [
            {"label": "主页", "url": "https://konachan.com"},
            {"label": "API", "url": "https://konachan.com/help/api"},
        ],
    },
    "e_shuushuu": {
        "group": "image",
        "label": "E-shuushuu",
        "title": "老牌二次元图站",
        "description": "以角色和作品图为主，但当前公开搜索接口尚未接通。",
        "best_for": "角色图、作品图。",
        "examples": ["Asuna", "Miku", "Rem", "Saber"],
        "hint_tags": ["角色", "作品"],
        "supports_search": True,
        "supports_mixed_home": True,
        "is_available": True,
        "status_note": None,
        "links": [
            {"label": "主页", "url": "https://e-shuushuu.net"},
            {"label": "API", "url": "https://e-shuushuu.net/api/v1/images/"},
        ],
    },
    "minitokyo": {
        "group": "image",
        "label": "MiniTokyo",
        "title": "壁纸与扫描图社区",
        "description": "适合老牌壁纸和扫描图内容，但当前证书与抓取兼容性有限。",
        "best_for": "壁纸图、扫描图。",
        "examples": ["Asuna", "Miku", "K-On!", "Fate"],
        "hint_tags": ["角色", "作品"],
        "supports_search": True,
        "supports_mixed_home": False,
        "is_available": False,
        "status_note": "MiniTokyo 当前证书与抓取兼容性有限，后端暂未接通",
        "links": [{"label": "主页", "url": "https://minitokyo.net"}],
    },
    "hpoi": {
        "group": "figure",
        "label": "Hpoi",
        "title": "中文手办与模型资料站",
        "description": "适合搜角色、商品名、厂商、系列，结果更偏手办与模型条目。",
        "best_for": "手办候选、厂商条目、再版关注。",
        "examples": ["初音未来", "良笑", "F:NEX", "尼尔 2B 手办"],
        "hint_tags": ["角色", "商品名", "厂商", "系列"],
        "supports_search": True,
        "supports_mixed_home": True,
        "is_available": True,
        "status_note": None,
        "links": [{"label": "主页", "url": "https://www.hpoi.net"}],
    },
    "amiami": {
        "group": "figure",
        "label": "AmiAmi",
        "title": "商品型手办商店",
        "description": "适合看在售和预售商品，但当前公开抓取容易被站点安全策略拦截。",
        "best_for": "在售手办、预约商品、品牌商品。",
        "examples": ["asuna figure", "miku scale figure", "good smile", "nendoroid"],
        "hint_tags": ["角色", "商品名", "厂商"],
        "supports_search": True,
        "supports_mixed_home": False,
        "is_available": False,
        "status_note": "AmiAmi 当前触发站点安全策略，后端公开搜索暂不可用",
        "links": [{"label": "主页", "url": "https://www.amiami.com"}],
    },
    "myfigurecollection": {
        "group": "figure",
        "label": "MyFigureCollection",
        "title": "手办资料与收藏社区",
        "description": "适合搜角色手办、PVC、比例款和品牌条目。",
        "best_for": "手办条目、系列手办、角色手办。",
        "examples": ["asuna figure", "miku scale figure", "good smile asuna", "alter saber"],
        "hint_tags": ["角色", "商品名", "厂商", "系列"],
        "supports_search": True,
        "supports_mixed_home": False,
        "is_available": False,
        "status_note": "MyFigureCollection 当前需要浏览器验证，后端公开搜索暂不可用",
        "links": [{"label": "主页", "url": "https://myfigurecollection.net"}],
    },
    "bangumi": {
        "group": "anime",
        "label": "Bangumi",
        "title": "中文动画资料与评分社区",
        "description": "适合查动画作品名和基础封面信息。",
        "best_for": "动画条目、中文作品查询。",
        "examples": ["刀剑神域", "葬送的芙莉莲", "blue archive", "初音未来"],
        "hint_tags": ["动画", "作品", "角色"],
        "supports_search": True,
        "supports_mixed_home": True,
        "is_available": True,
        "status_note": None,
        "links": [
            {"label": "主页", "url": "https://bgm.tv"},
            {"label": "开发者平台", "url": "https://bgm.tv/dev"},
        ],
    },
    "anilist": {
        "group": "anime",
        "label": "AniList",
        "title": "公开 API 动画数据库",
        "description": "适合快速搜动画作品并拿到封面、类型和状态。",
        "best_for": "动画条目、番剧搜索、作品发现。",
        "examples": ["Sword Art Online", "Asuna", "Blue Archive", "Frieren"],
        "hint_tags": ["动画", "作品", "角色"],
        "supports_search": True,
        "supports_mixed_home": True,
        "is_available": True,
        "status_note": None,
        "links": [
            {"label": "主页", "url": "https://anilist.co"},
            {"label": "API 文档", "url": "https://anilist.gitbook.io/anilist-apiv2-docs"},
        ],
    },
    "myanimelist": {
        "group": "anime",
        "label": "MyAnimeList",
        "title": "大型动画数据库",
        "description": "适合作为作品检索来源，但当前后端公开搜索暂未接通。",
        "best_for": "动画条目、番剧资料。",
        "examples": ["Sword Art Online", "Frieren", "Blue Archive", "Asuna"],
        "hint_tags": ["动画", "作品", "角色"],
        "supports_search": True,
        "supports_mixed_home": True,
        "is_available": True,
        "status_note": "当前默认通过 Jikan 提供公开搜索；如配置 MAL Client ID，可切换到官方 API",
        "links": [
            {"label": "主页", "url": "https://myanimelist.net"},
            {"label": "官方 API", "url": "https://myanimelist.net/apiconfig/references/api/v2"},
            {"label": "Jikan", "url": "https://docs.api.jikan.moe/"},
        ],
    },
    "anidb": {
        "group": "anime",
        "label": "AniDB",
        "title": "老牌动画数据库",
        "description": "作品资料丰富，但当前公开搜索接入尚未完成。",
        "best_for": "动画资料、条目检索。",
        "examples": ["Sword Art Online", "Asuna", "Fate", "Miku"],
        "hint_tags": ["动画", "作品"],
        "supports_search": True,
        "supports_mixed_home": False,
        "is_available": False,
        "status_note": "AniDB 官方 API 当前在本运行环境中 TLS 握手超时，后端暂未接通",
        "links": [
            {"label": "主页", "url": "https://anidb.net"},
            {"label": "API 说明", "url": "https://wiki.anidb.net/API"},
        ],
    },
    "sketchfab": {
        "group": "asset",
        "label": "Sketchfab",
        "title": "公开 3D 模型平台",
        "description": "适合找 3D 角色模型、资产和可预览模型。",
        "best_for": "3D 模型、角色资产、展示模型。",
        "examples": ["anime girl", "miku", "sci-fi character", "mecha"],
        "hint_tags": ["3D", "角色", "模型"],
        "supports_search": True,
        "supports_mixed_home": True,
        "is_available": True,
        "status_note": None,
        "links": [
            {"label": "主页", "url": "https://sketchfab.com"},
            {"label": "Data API", "url": "https://sketchfab.com/developers/data-api/v3"},
        ],
    },
    "booth": {
        "group": "asset",
        "label": "BOOTH",
        "title": "创作商品与素材市场",
        "description": "适合找 3D 模型、VRChat 角色、素材包和创作商品。",
        "best_for": "素材、模型资源、创作商品。",
        "examples": ["vrm", "miku", "anime girl", "blue archive"],
        "hint_tags": ["3D", "模型", "素材"],
        "supports_search": True,
        "supports_mixed_home": True,
        "is_available": True,
        "status_note": None,
        "links": [{"label": "主页", "url": "https://booth.pm"}],
    },
    "bowlroll": {
        "group": "asset",
        "label": "BowlRoll",
        "title": "模型资源分享站",
        "description": "适合 MMD、模型和动作资源搜索，当前走公开关键词 JSON 接口。",
        "best_for": "模型资源、MMD 资源。",
        "examples": ["mmd", "vrm", "miku", "model"],
        "hint_tags": ["3D", "模型", "资源"],
        "supports_search": True,
        "supports_mixed_home": True,
        "is_available": True,
        "status_note": None,
        "links": [{"label": "主页", "url": "https://bowlroll.net"}],
    },
    "aplaybox": {
        "group": "asset",
        "label": "aPlayBox / 模之屋",
        "title": "中文 3D 资源站",
        "description": "适合中文 3D 资源与模型检索，但当前页面主要依赖前端应用和站内接口。",
        "best_for": "中文 3D 模型、资产资源。",
        "examples": ["miku", "anime girl", "mecha", "vrm"],
        "hint_tags": ["3D", "模型", "资源"],
        "supports_search": True,
        "supports_mixed_home": False,
        "is_available": False,
        "status_note": "aPlayBox / 模之屋 当前未暴露稳定公开搜索接口，页面依赖前端应用加载，后端暂未接通",
        "links": [{"label": "主页", "url": "https://www.aplaybox.com"}],
    },
}

SITE_ORDER = list(SITE_REGISTRY)
HOME_SITE_ORDER = ["all", *SITE_ORDER]

SITE_PROFILES = {
    "all": {
        "label": "All",
        "title": "跨站混合搜索",
        "description": "自然输入关键词，系统会按公开站点分别解释并聚合结果。",
        "best_for": "适合还不确定想看图、角色图集、手办还是动画条目时使用。",
        "examples": ["初音未来", "asuna", "genshin impact", "良笑 初音"],
        "hint_tags": ["角色名", "作品名", "作者名", "商品名"],
        "group": "all",
        "supports_search": False,
        "supports_mixed_home": True,
        "is_available": True,
        "status_note": None,
        "links": [],
    },
    **SITE_REGISTRY,
}


def sites_for_mode(site_mode: str | None) -> list[str]:
    if not site_mode or site_mode == "all":
        return SITE_ORDER.copy()
    return [site_mode] if site_mode in SITE_ORDER else [SITE_ORDER[0]]


def sites_for_group(group_id: str | None, *, include_all: bool = False) -> list[str]:
    if not group_id or group_id == "all":
        sites = SITE_ORDER.copy()
    else:
        sites = [site for site, profile in SITE_REGISTRY.items() if profile["group"] == group_id]
    return (["all"] + sites) if include_all else sites
